// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebWMS.Core.DbContexts;

#nullable disable

namespace WebWMS.Core.Migrations
{
    [DbContext(typeof(WMSDbContext))]
    [Migration("20230904071603_up-customer")]
    partial class upcustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebWMS.Core.Domain.Asns.Asn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("actual_qty")
                        .HasColumnType("int");

                    b.Property<string>("asn_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("asn_qty")
                        .HasColumnType("int");

                    b.Property<byte>("asn_status")
                        .HasColumnType("tinyint");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("damage_qty")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<string>("goods_owner_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<int>("more_qty")
                        .HasColumnType("int");

                    b.Property<int>("shortage_qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<int>("sorted_qty")
                        .HasColumnType("int");

                    b.Property<int>("spu_id")
                        .HasColumnType("int");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Asns", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Asns.Asnsort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("asn_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<int>("sorted_qty")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Asnsort", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Companys.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Companys", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Delete")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("MoblePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Dispatchlists.Dispatchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("actual_qty")
                        .HasColumnType("int");

                    b.Property<string>("carrier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("damage_qty")
                        .HasColumnType("int");

                    b.Property<string>("dispatch_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("dispatch_status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("freightfee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("intrasit_qty")
                        .HasColumnType("int");

                    b.Property<int>("lock_qty")
                        .HasColumnType("int");

                    b.Property<string>("package_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_person")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("package_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("package_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("picked_qty")
                        .HasColumnType("int");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<int>("sign_qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("waybill_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weighing_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weighing_person")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("weighing_qty")
                        .HasColumnType("int");

                    b.Property<decimal>("weighing_weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Dispatchlists", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Dispatchlists.Dispatchpicklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("dispatchlistId")
                        .HasColumnType("int");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("bit");

                    b.Property<int>("pick_qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("dispatchlistId");

                    b.ToTable("Dispatchpicklists", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Freightfees.Freightfee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("arrival_city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carrier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departure_city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<decimal>("min_payment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("price_per_volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("price_per_weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Freightfees", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.GoodsOwners.Goodsowner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goods_owner_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Goodsowners", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Goodslocations.Goodslocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<string>("layer_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("location_heigth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("location_length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("location_load")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("location_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("location_volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("location_width")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("roadway_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shelf_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tag_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("warehouse_area_id")
                        .HasColumnType("int");

                    b.Property<string>("warehouse_area_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("warehouse_area_property")
                        .HasColumnType("tinyint");

                    b.Property<int>("warehouse_id")
                        .HasColumnType("int");

                    b.Property<string>("warehouse_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Goodslocations", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Rolemenus.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("menu_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sort")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("vue_directory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vue_path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vue_path_detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menus", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Rolemenus.Rolemenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("authority")
                        .HasColumnType("tinyint");

                    b.Property<int>("menu_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("userrole_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rolemenus", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Skus.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<int>("parent_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Categorys", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Skus.Sku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("lenght")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("sku_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sku_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("volume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SpuId");

                    b.ToTable("Skus", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Skus.Spu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("bar_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<byte>("length_unit")
                        .HasColumnType("tinyint");

                    b.Property<string>("origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spu_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spu_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spu_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<byte>("volume_unit")
                        .HasColumnType("tinyint");

                    b.Property<byte>("weight_unit")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Spus", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Stockadjusts.Stockadjust", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("bit");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("job_type")
                        .HasColumnType("tinyint");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<int>("source_table_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Stockadjusts", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Stockfreezes.Stockfreeze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("job_type")
                        .HasColumnType("bit");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Stockfreezes", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Stockmoves.Stockmove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dest_googs_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("handle_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("move_status")
                        .HasColumnType("tinyint");

                    b.Property<int>("orig_goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Stockmoves", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Stockprocesss.Stockprocess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("job_type")
                        .HasColumnType("bit");

                    b.Property<bool>("process_status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("process_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("processor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Stockprocesss", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Stockprocesss.Stockprocessdetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockprocessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_source")
                        .HasColumnType("bit");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("bit");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StockprocessId");

                    b.ToTable("Stockprocessdetails", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Stocks.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_freeze")
                        .HasColumnType("bit");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Stocktakings.Stocktaking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("book_qty")
                        .HasColumnType("int");

                    b.Property<int>("counted_qty")
                        .HasColumnType("int");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("difference_qty")
                        .HasColumnType("int");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("handle_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("job_status")
                        .HasColumnType("bit");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Stocktakings", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Warehouseareas.Warehousearea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("area_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("area_property")
                        .HasColumnType("tinyint");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<int>("parent_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("warehouse_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Warehouseareas", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Warehouses.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("warehouse_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.suppliers.supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Dispatchlists.Dispatchpicklist", b =>
                {
                    b.HasOne("WebWMS.Core.Domain.Dispatchlists.Dispatchlist", "dispatchlist")
                        .WithMany("detailList")
                        .HasForeignKey("dispatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dispatchlist");
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Skus.Sku", b =>
                {
                    b.HasOne("WebWMS.Core.Domain.Skus.Spu", "Spu")
                        .WithMany("detailList")
                        .HasForeignKey("SpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spu");
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Stockprocesss.Stockprocessdetail", b =>
                {
                    b.HasOne("WebWMS.Core.Domain.Stockprocesss.Stockprocess", "Stockprocess")
                        .WithMany("detailList")
                        .HasForeignKey("StockprocessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stockprocess");
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Dispatchlists.Dispatchlist", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Skus.Spu", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("WebWMS.Core.Domain.Stockprocesss.Stockprocess", b =>
                {
                    b.Navigation("detailList");
                });
#pragma warning restore 612, 618
        }
    }
}
